import Head from "next/head";
import Nav from "../../components/Nav";
import Result from "../../components/Result";
import request from "../../utiles/request";

export default function Home({ results }) {
  // console.log("Result is the , ", results.articles);
  return (
    <>
      <Head>
        <title>Latest News</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-6">
        <Nav />
        <Result results={results} />
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  // Construct the fetch URL based on the genre
  let fetchUrl;
  if (genre == undefined) {
    fetchUrl = request.business.url;
  } else {
    fetchUrl = `${genre}${request[genre]?.url}`;
  }
console.log("fetchURL is", fetchUrl)
  // Fetch data from the constructed URL
  const requests = await fetch(
    `https://newsapi.org/v2/top-headlines?country=us&category=${fetchUrl}`
  ).then((res) => res.json());

  return {
    props: { results: requests }, // will be passed to the page component as props
  };
}

