import Head from 'next/head'

import Header from '../../components/Header'
import Nav from '../../components/Nav'
import Result from '../../components/Result'
import request from '../../utiles/request'


export default function Home({results}) {

  return (
    <>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
      <Header />
      <Nav />
      <Result results={results} />
     </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const requests = await fetch(`https://api.themoviedb.org/3${request[genre]?.url || request.fetchTrading.url}`).then(res => res.json())
 console.log("requests is :", requests)

  return {
    props: { results: requests.results }, // will be passed to the page component as props
    
  }
}
 